services:

    ApiBundle\EventSubscriber\Serializer\SubjectEnricherSubscriber:
        class: ApiBundle\EventSubscriber\Serializer\SubjectEnricherSubscriber
        arguments:
            - '@picking.picking_manager'
            - '@Wynd\LexBundle\Service\LexTools'
            - '@ApiBundle\Service\OrderMetadataCalculatorService'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: jms_serializer.event_subscriber }

    ApiBundle\Event\OrderHistorisationListener:
        class: ApiBundle\Event\OrderHistorisationListener
        tags:
          - {name: doctrine.event_listener, event: onFlush }
