services:
    cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ['%kernel.cache_dir%']

    api_bundle.fly_system_utils:
        class: ApiBundle\Service\FlySystemUtils

    api_bundle.parser_tools:
        class: ApiBundle\Service\ParserTools

    api_bundle.cloudinary:
        class: ApiBundle\Service\ClientCloudinary
        arguments: ["%cloudinary%"]

    api_cybersource:
        class: ApiBundle\Service\Cybersource
        arguments:
            - "@request_stack"
            - "@logger"
            - "@event_dispatcher"
            - "%currency%"
            - "%cbs%"
            - "@api.order_manager"
            - '@ApiBundle\Amqp\Publisher\MailMessagePublisher'
            - %order_alert_emails%
        tags:
            - { name: monolog.logger, channel: cbs }

    api_bundle.send_invoice:
            class: ApiBundle\Service\SendInvoice
            arguments: ["%maf_param%"]

    api_bundle.pos_export_file:
        class: ApiBundle\Service\ExportPOSService
        arguments: ['@api.order_manager']

    api_bundle.spellout_number:
        class: ApiBundle\Twig\Extension\SpelloutNumberExtension
        tags:
            - { name: twig.extension }

    api_bundle.resolve_serializer_subscriber:
        class: ApiBundle\EventSubscriber\ResolveSerializerSubscriber
        arguments: ['@request_stack', '@api.order_manager']
        tags:
            - { name: jms_serializer.event_subscriber }

    ApiBundle\EventSubscriber\Serializer\SubjectEnricherSubscriber:
        class: ApiBundle\EventSubscriber\Serializer\SubjectEnricherSubscriber
        arguments:
            - '@picking.picking_manager'
            - '@Wynd\LexBundle\Service\LexTools'
            - '@ApiBundle\Service\OrderMetadataCalculatorService'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: jms_serializer.event_subscriber }

    api_bundle.transaction_collector.subscriber:
        class: ApiBundle\EventSubscriber\TransactionCollectorSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    api_bundle.order_item_invalidator.subscriber:
        class: ApiBundle\EventSubscriber\ProductInvalidatorSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_subscriber }

    api_bundle.redis.cache_flush_scheduler:
        class: ApiBundle\Cache\RedisCacheFlushScheduler
        arguments:
            - '@ApiBundle\Amqp\Publisher\RedisCacheFlushMessagePublisher'

    app.order.status.listener:
        class: ApiBundle\EventListener\OrderEventListener
        arguments:
            - '@event_dispatcher'
            - '@api_bundle.redis.cache_flush_scheduler'
            - '@picking.picking_manager'
            - '@ApiBundle\Amqp\Publisher\CaptureMessagePublisher'
        tags:
            - { name: kernel.event_subscriber }

    ApiBundle\Amqp\:
        resource: '../../src/ApiBundle/Amqp'
        exclude: '../../src/ApiBundle/Amqp/Message'
        autowire: true
        public: true

    wynd.cache_component:
        class: WyndStorageManager\Component\Cache
        arguments: ["%api_sdk_cache_manager_config%"]

    api_bo_order_service:
        class: ApiBundle\Manager\Bo\OrderBoManager
        arguments: ["@api.order_manager", "@knp_paginator", "%default_pagination_range%", "@request_stack"]

    api.order_manager:
        class: ApiBundle\Manager\OrderManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@fos_elastica.finder.serialization.order"
            - "@knp_paginator"
            - "@request_stack"
            - %default_pagination_range%
            - "@api.destination_manager"
            - WyndApi\WyndApiCoreBundle\Entity\Order\OrderInterface
            - '@Wynd\LexBundle\Service\LexTools'
            - '@api.country.repository'

    ApiBundle\Service\Order\OrderFactory:
        class: ApiBundle\Service\Order\OrderFactory
        arguments:
            - "@doctrine.orm.entity_manager"

    api.country.repository:
        class: WyndApi\WyndApiCoreBundle\Repository\CountryRepository
        factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
        arguments:
            - WyndApi\WyndApiCoreBundle\Entity\Country

    api_bundle.product_repository:
        class: ApiBundle\Repository\IndexedProductRepository
        arguments:
            - '@fos_elastica.finder.serialization.product'
            - '@maf.elasticsearch.low_level.client'
            - '%elasticsearch_index_name%'

    api.order_item.repository:
        class: WyndApi\WyndApiCoreBundle\Repository\OrderItemRepository
        factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
        arguments:
            - WyndApi\WyndApiCoreBundle\Entity\Order\OrderItem

    api_bundle.pos_export_bo_file:
            class: ApiBundle\Service\ExportPOSBOService
            arguments: ['@api_bo_order_service', '@ApiBundle\Service\OrderMetadataCalculatorService']

    ApiBundle\EventSubscriber\Payment\PaymentSubscriber:
        class: ApiBundle\EventSubscriber\Payment\PaymentSubscriber
        autowire: true
        arguments:
            $boAdminEmails: '%bo_admin_emails%'
        tags: ['kernel.event_subscriber']

    ApiBundle\Amqp\Publisher\MailMessagePublisher:
        class: ApiBundle\Amqp\Publisher\MailMessagePublisher
        arguments:
            $producer: '@old_sound_rabbit_mq.email_scheduler_producer'

    ApiBundle\Amqp\Publisher\RedisCacheFlushMessagePublisher:
        class: ApiBundle\Amqp\Publisher\RedisCacheFlushMessagePublisher
        arguments:
            $producer: '@old_sound_rabbit_mq.redis_cache_flush_scheduler_producer'

    ApiBundle\Amqp\Publisher\CaptureMessagePublisher:
        class: ApiBundle\Amqp\Publisher\CaptureMessagePublisher
        arguments:
            $producer: '@old_sound_rabbit_mq.capture_scheduler_producer'

    ApiBundle\Mailing\:
        resource: '../../src/ApiBundle/Mailing'
        autoconfigure: true
        autowire: true
        arguments:
            $mailFrom: '%mail_from%'

    ApiBundle\Mailing\OrderInvoiceMailSender:
        class: ApiBundle\Mailing\OrderInvoiceMailSender
        autowire: true
        autoconfigure: true
        arguments:
            $kernelRootDir: '%kernel.root_dir%'

    ApiBundle\Amqp\Consumers\:
        resource: '../../src/ApiBundle/Amqp/Consumers'
        autoconfigure: true
        autowire: true

    ApiBundle\Encoding\:
        resource: '../../src/ApiBundle/Encoding'
        autoconfigure: true
        autowire: true

    ApiBundle\Http\:
        resource: '../../src/ApiBundle/Http'
        autoconfigure: true
        autowire: true
        arguments:
            $cbsConfig: '%cbs%'
            $endpointUrlPath: '%cbs_query_url_path%'

    ApiBundle\Amqp\Consumers\RedisCacheFlusherConsumer:
        class: ApiBundle\Amqp\Consumers\RedisCacheFlusherConsumer
        autoconfigure: true
        autowire: true
        arguments:
            $enableApiCacheWarmUp: '%enable_api_cache_warmup%'
            $env: '%kernel.environment%'

    api.product_manager:
        class: ApiBundle\Manager\ProductManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - WyndApi\WyndApiCoreBundle\Entity\ProductInterface
            - "@fos_elastica.finder.serialization.product"
            - "@wynd_api.request.paginator"
            - "@api.product_price_manager"
            - '@api_bundle.product_repository'
            - '@ApiBundle\Manager\Formatter\ProductListFormatter'
            - '%default_pagination_range%'
        calls:
            - [ setResolveTargetEntities, ["%wynd_resolve_target_entities%"]]

    maf.wynd_api:
        class: WyndApiSDK\WyndApiClient
        arguments:
            - "%api_url%"
            - "%api_user%"
            - "%api_password%"
            - "@logger"
            - "%api_sdk_cache_manager_config%"
        tags:
            - { name: monolog.logger, channel: wynd_api }

    api_bundle.customers_export_bo_file:
        class: ApiBundle\Service\ExportCustomersBOService
        arguments: ['@api.customer_manager']

    ApiBundle\Service\OrderMetadataCalculatorService:
        class: ApiBundle\Service\OrderMetadataCalculatorService
        arguments:
            - "%wynd_lex.volume_margin%"

    ApiBundle\Event\OrderHistorisationListener:
        class: ApiBundle\Event\OrderHistorisationListener
        tags:
          - {name: doctrine.event_listener, event: onFlush }

    ApiBundle\Manager\Formatter\ProductListFormatter:
        class: ApiBundle\Manager\Formatter\ProductListFormatter

    maf.elasticsearch.low_level.client:
        class: Elasticsearch\Client
        factory: [Elasticsearch\ClientBuilder, fromConfig]
        arguments: [{ hosts: ['%env(ELASTICSEARCH_URL)%'] }]